# bigvul:177947 / CVE-2011-0064
# Generated by VulValidate/docker_repro/build_case.py.  The build context is the sample's
# own directory -- the two stored function bodies, dynamic_evidence/ with the driver, the
# attack input and repro.sh -- and nothing else from the build machine.
#
# Build:  docker build -t lzhan011/vulvalidate-repro:bigvul-177947 <context>
# Run:    docker run --rm --network none lzhan011/vulvalidate-repro:bigvul-177947
FROM vulvalidate/repro-base:1
LABEL org.opencontainers.image.title="VulValidate reproduction bigvul:177947"
LABEL vulvalidate.sample="bigvul:177947"
LABEL vulvalidate.cve="CVE-2011-0064"
LABEL vulvalidate.project="harfbuzz"
COPY sample/ /repro/
RUN find /repro -name '*.sh' -exec chmod +x {} +
WORKDIR /repro/dynamic_evidence
CMD ["bash", "/repro/dynamic_evidence/repro.sh"]
