# bigvul:177823 / CVE-2011-2895
# Generated by VulValidate/docker_repro/build_case.py.  The build context is the sample's
# own directory -- the two stored function bodies, dynamic_evidence/ with the driver, the
# attack input and repro.sh -- and nothing else from the build machine.
#
# Build:  docker build -t lzhan011/vulvalidate-repro:bigvul-177823 <context>
# Run:    docker run --rm --network none lzhan011/vulvalidate-repro:bigvul-177823
FROM vulvalidate/repro-base:1
LABEL org.opencontainers.image.title="VulValidate reproduction bigvul:177823"
LABEL vulvalidate.sample="bigvul:177823"
LABEL vulvalidate.cve="CVE-2011-2895"
LABEL vulvalidate.project="libxfont"
COPY sample/ /repro/
RUN find /repro -name '*.sh' -exec chmod +x {} +
WORKDIR /repro/dynamic_evidence
CMD ["bash", "/repro/dynamic_evidence/repro.sh"]
